name: gallery
description: "Mocked gallery app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  #logic
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  crypto: ^3.0.6

  #storage
  shared_preferences: ^2.5.3

  #config
  equatable: ^2.0.7

  #view
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
